src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[Vich\Uploadable]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, \Serializable
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 20)]
    private ?string $phone = null;

    // NOTE: This is not a mapped field of entity metadata, just a simple property.
    #[Vich\UploadableField(mapping: 'profile', fileNameProperty: 'imgName')]
    #[Assert\File(
        maxSize : '2048k',
        mimeTypes : ["image/jpeg", "image/png", "image/bmp"],
    )]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imgName = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $userType = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Company $company = null;

    #[ORM\OneToMany(targetEntity: Offer::class, mappedBy: 'owner')]
    private Collection $offers;

    public function __construct()
    {
        $this->offers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImgName(): ?string
    {
        return $this->imgName;
    }

    public function setImgName(?string $imgName): static
    {
        $this->imgName = $imgName;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUserType(): ?string
    {
        return $this->userType;
    }

    public function setUserType(?string $userType): static
    {
        $this->userType = $userType;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection<int, Offer>
     */
    public function getOffers(): Collection
    {
        return $this->offers;
    }

    public function addOffer(Offer $offer): static
    {
        if (!$this->offers->contains($offer)) {
            $this->offers->add($offer);
            $offer->setOwner($this);
        }

        return $this;
    }

    public function removeOffer(Offer $offer): static
    {
        if ($this->offers->removeElement($offer)) {
            // set the owning side to null (unless already changed)
            if ($offer->getOwner() === $this) {
                $offer->setOwner(null);
            }
        }

        return $this;
    }

    public function getUserName()
    {
        return $this->getLastName() . ' ' . $this->getFirstName();;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
        ));
    }

    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->email,
            $this->password,
        ) = unserialize($serialized);
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use App\Service\IdentifierChecker;
use Doctrine\ORM\EntityManagerInterface;
use ParagonIE\Halite\KeyFactory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Contracts\Translation\TranslatorInterface;
use ParagonIE\Halite\Symmetric\Crypto as SymmetricCrypto;
use ParagonIE\HiddenString\HiddenString;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\HttpKernel\KernelInterface;

class SecurityController extends AbstractController
{

    public function __construct(
        private IdentifierChecker $identifierChecker,
        private TranslatorInterface $translator,
        private UserPasswordHasherInterface $hash,
        private KernelInterface $kernel,
        private $keyFilePath,
        private UserPasswordHasherInterface $passwordHasher,
        private EntityManagerInterface $em
    )
    {
        $this->keyFilePath = $keyFilePath;
    }

    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('app_homepage');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route(path: '/forgot-pass', name: 'app_forgot_pass')]
    public function forgotPass(Request $request, UserRepository $userRepository): Response
    {
        $form = $this->createFormBuilder()
            ->add('email', EmailType::class, [
                'label' => 'bo.user.email',
                'required' => true
            ])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer les données du formulaire
            $data = $form->getData();
            $isIdentifierExist = $this->identifierChecker->identifierExist($data['email']);
            if(!$isIdentifierExist){
                $this->addFlash('error', $this->translator->trans('app.identifier.not.exist'));
                return $this->redirectToRoute('app_forgot_pass');
            }
            $user = $userRepository->findOneBy(['email' => $data['email']]);
            $key = KeyFactory::generateEncryptionKey();
            KeyFactory::save($key, $this->keyFilePath);
            $userId = strval($user->getId());
            $encryptId = SymmetricCrypto::encrypt(new HiddenString($userId), $key);
            
            return $this->redirectToRoute('app_change_pass', ['encryptId' => $encryptId]);
        }

        return $this->render('security/forgot_pass.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route(path: '/change-pass/{encryptId}', name: 'app_change_pass')]
    public function changePass(string $encryptId, Request $request, IdentifierChecker $identifierChecker, UserRepository $userRepository): Response
    {
        $key = KeyFactory::loadEncryptionKey($this->keyFilePath);
        $decryptId = SymmetricCrypto::decrypt($encryptId, $key); 
        $user = $userRepository->find(intval($decryptId->getString()));
        $form = $this->createFormBuilder()
            ->add('password', RepeatedType::class, [
                'required' => true,
                'type' => PasswordType::class,
                'first_options' => [
                    'label' => 'bo.user.password',
                    'attr' => [
                        'autocomplete' => 'new-password'
                    ]
                ],
                'second_options' => [
                    'label' => 'bo.user.password.confirm',
                    'attr' => [
                        'autocomplete' => 'new-password'
                    ]
                ],
            ])
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer les données du formulaire
            $data = $form->getData();
            $encodedPassword = $this->passwordHasher->hashPassword(
                $user,
                $data['password']
            );
            $user->setPassword($encodedPassword);
            $this->em->flush();

            $this->addFlash('success', 'Votre mot de passe a été modifier avec succès.');
            return $this->redirectToRoute('app_login');
        }

        return $this->render('security/change_pass.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/security/change_pass.html.twig
{% extends 'auth.html.twig' %}

{% block title %}{{'app.change.pass.title'|trans}}{% endblock %}

{% block body %}

    <div class="col-lg-10 offset-lg-1">
        <h3 class="mb-3">{{'app.change.pass.title'|trans}}</h3>
        {# flash message #}
        {% include 'partials/_flash.html.twig' %}
        <div class="bg-white shadow rounded">
            <div class="row">
                <div class="col-md-7 pe-0">
                    <div class="form-left h-100 py-5 px-5">
                        {{form_start(form)}}
                                <div class="col-12">
                                    {{ form_row(form.password.first, {
                                        attr: {
                                            'class': 'form-control'
                                        }
                                    }) }}
                                    {{ form_row(form.password.second, {
                                        attr: {
                                            'class': 'form-control'
                                        }
                                    }) }}
                                </div>

                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary px-4 float-end mt-4 mb-4">{{'app.save'|trans}}</button>
                                </div>
                        {{form_end(form)}}
                    </div>
                </div>
                <div class="col-md-5 ps-0 d-none d-md-block">
                    <div class="form-right h-100 bg-primary text-white text-center pt-5">
                        <i class="bi bi-bootstrap"></i>
                    </div>
                </div>
            </div>
        </div>
        <p class="text-end text-secondary mt-3">Bootstrap 5 Login Page Design</p>
    </div>

{% endblock %}

templates/security/forgot_pass.html.twig
{% extends 'auth.html.twig' %}

{% block title %}{{'app.check.identifier.title'|trans}}{% endblock %}

{% block body %}

    <div class="col-lg-10 offset-lg-1">
        <h3 class="mb-3">{{'app.check.identifier.title'|trans}}</h3>
        {# flash message #}
        {% include 'partials/_flash.html.twig' %}
        <div class="bg-white shadow rounded">
            <div class="row">
                <div class="col-md-7 pe-0">
                    <div class="form-left h-100 py-5 px-5">
                        {{form_start(form)}}
                                <div class="col-12">
                                    {{ form_row(form.email, {
                                        label: 'bo.user.email'|trans,
                                        attr: {
                                            'class': 'form-control'
                                        }
                                    }) }}
                                </div>

                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary px-4 float-end mt-4 ">{{'app.check'|trans}}</button>
                                </div>
                        {{form_end(form)}}
                    </div>
                </div>
                <div class="col-md-5 ps-0 d-none d-md-block">
                    <div class="form-right h-100 bg-primary text-white text-center pt-5">
                        <i class="bi bi-bootstrap"></i>
                    </div>
                </div>
            </div>
        </div>
        <p class="text-end text-secondary mt-3">Bootstrap 5 Login Page Design</p>
    </div>

{% endblock %}

templates/security/login.html.twig
{% extends 'auth.html.twig' %}

{% block title %}{{'app.login.title'|trans}}{% endblock %}

{% block body %}

    <div class="col-lg-10 offset-lg-1">
        <h3 class="mb-3">{{'app.login.title'|trans}}</h3>
        {# flash message #}
        {% include 'partials/_flash.html.twig' %}
        <div class="bg-white shadow rounded">
            <div class="row">
                <div class="col-md-7 pe-0">
                    <div class="form-left h-100 py-5 px-5">
                        <form method="post" class="row g-4">
                                {% if error %}
                                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                                {% endif %}

                                {% if app.user %}
                                    <div class="mb-3">
                                        You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
                                    </div>
                                {% endif %}
                                <div class="col-12">
                                    <label for="inputEmail">{{ 'bo.user.email'|trans }}<span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <div class="input-group-text"><i class="bi bi-person-fill"></i></div>
                                        <input type="email" class="form-control" value="{{ last_username }}" name="email" id="inputEmail"  placeholder="{{ 'bo.user.placeholder.email'|trans }}" autocomplete="email" required autofocus>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <label for="password">{{ 'bo.user.password'|trans }}<span class="text-danger">*</span></label>
                                    <div class="input-group">
                                        <div class="input-group-text"><i class="bi bi-lock-fill"></i></div>
                                        <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required placeholder="{{ 'bo.user.placeholder.password'|trans }}">
                                    </div>
                                </div>
                                <input type="hidden" name="_csrf_token"
                                    value="{{ csrf_token('authenticate') }}"
                                >
                                <div class="col-sm-6">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="inlineFormCheck" name="_remember_me">
                                        <label class="form-check-label" for="inlineFormCheck">{{ 'bo.user.remember.me'|trans }}</label>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <a href="{{path('app_forgot_pass')}}" class="float-end text-primary">{{'bo.user.forgot.pass'|trans}}</a>
                                </div>

                                <div class="col-12">
                                    <button type="submit" class="btn btn-primary px-4 float-end mt-4">{{'app.login'|trans}}</button>
                                </div>
                        </form>
                    </div>
                </div>
                <div class="col-md-5 ps-0 d-none d-md-block">
                    <div class="form-right h-100 bg-primary text-white text-center pt-5">
                        <i class="bi bi-bootstrap"></i>
                        <h2 class="fs-1">{{'app.login.greetings'|trans}}</h2>
                    </div>
                </div>
            </div>
        </div>
        <p class="text-end text-secondary mt-3">Bootstrap 5 Login Page Design</p>
    </div>

{% endblock %}